import React from 'react';

export default function FleetTrackExportDigest({ history = [], weekLabel = 'Week of Sep 23–29, 2025' }) {
  if (!Array.isArray(history) || history.length === 0) {
    return <p>No export data available for {weekLabel}.</p>;
  }

  const totalExports = history.length;
  const formatCounts = history.reduce((acc, entry) => {
    acc[entry.format] = (acc[entry.format] || 0) + 1;
    return acc;
  }, {});

  const tripCounts = history.reduce((acc, entry) => {
    acc[entry.tripId] = (acc[entry.tripId] || 0) + 1;
    return acc;
  }, {});

  const topTrip = Object.entries(tripCounts).sort((a, b) => b[1] - a[1])[0];

  return (
    <div className="p-6 bg-white rounded-xl shadow-md text-sm space-y-6">
      <h1 className="text-2xl font-bold">📬 FleetTrack Weekly Export Digest</h1>
      <p><strong>Reporting Period:</strong> {weekLabel}</p>
      <p><strong>Total Exports:</strong> {totalExports}</p>
      <p><strong>PDF Exports:</strong> {formatCounts.pdf ?? 0}</p>
      <p><strong>CSV Exports:</strong> {formatCounts.csv ?? 0}</p>

      {/* Highlights */}
      {topTrip && (
        <div className="space-y-2">
          <h2 className="text-lg font-semibold">🚚 Top Exported Trip</h2>
          <p>Trip <code>{topTrip[0]}</code> was exported {topTrip[1]} times.</p>
        </div>
      )}

      {/* Footer */}
      <div className="border-t pt-4 text-xs text-gray-500">
        <p>This digest was auto-generated by FleetTrack’s export engine.</p>
        <p>Export timestamp: {new Date().toLocaleString()}</p>
      </div>
    </div>
  );
}